# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('recurring', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=500)),
                ('created', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_send', models.DateTimeField(null=True)),
                ('next_send', models.DateTimeField()),
                ('interval', models.IntegerField(default=1, null=True)),
                ('interval_type', models.CharField(choices=[('day', 'day(s)'), ('week', 'week(s)'), ('month', 'month(s)'), ('year', 'year(s)')], default='week(s)', max_length=50, null=True)),
                ('snooze', models.NullBooleanField()),
                ('snooze_interval', models.IntegerField(null=True)),
                ('snooze_interval_type', models.CharField(max_length=50, null=True)),
                ('snooze_last_send', models.DateTimeField(null=True)),
                ('snooze_next_send', models.DateTimeField(null=True)),
                ('warning', models.BooleanField(default=True)),
                ('warning_interval', models.IntegerField(default=1, null=True)),
                ('warning_interval_type', models.CharField(choices=[('day', 'day(s)'), ('week', 'week(s)'), ('month', 'month(s)'), ('year', 'year(s)')], default='day(s)', max_length=50)),
                ('warning_next_send', models.DateTimeField(null=True)),
                ('in_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('event_id', models.IntegerField(null=True)),
                ('sent', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
