# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageLog',
            new_name='MessageLogEvent',
        ),
    ]
