# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLogPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('person_id', models.IntegerField(null=True)),
                ('sent', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('created', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('last_send', models.DateTimeField(null=True)),
                ('next_send', models.DateTimeField()),
                ('interval', models.IntegerField(default=1, null=True)),
                ('interval_type', models.CharField(choices=[('day', 'day(s)'), ('week', 'week(s)'), ('month', 'month(s)'), ('year', 'year(s)')], default='week(s)', max_length=50, null=True)),
                ('snooze', models.NullBooleanField()),
                ('snooze_interval', models.IntegerField(null=True)),
                ('snooze_interval_type', models.CharField(max_length=50, null=True)),
                ('snooze_last_send', models.DateTimeField(null=True)),
                ('snooze_next_send', models.DateTimeField(null=True)),
                ('in_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
