# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notification_method',
            field=models.CharField(choices=[('text', 'text'), ('email', 'email'), ('both', 'both')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='message',
            field=models.TextField(),
        ),
    ]
